### ISSUE TITLE
Error importing bookmarks

### ISSUE THREAD

**Issue by gregf** [jonschoning/espial#15]
```
"Error in $: parsing [] failed, expected Array, but encountered Object"
```

I would rather not post my entire bookmarks file publically can I email a private link to you?

I should note I exported my bookmarks in firefox 77.0.1 as json.

**Comment by jonschoning** [comment]
oh, actually the import json feature is identical to the json format that pinboard gives you when export from pinboard.  

i.e. the import feature as it works now wasn't initially intended to handle json export from a browser.

Let me think for a bit and see what the easiest way to import from a browser might be.

I think pinboard allows you to import bookmark html files, so that might be route i look at for importing from a browser

**Comment by jonschoning** [comment]
added a command

5b. Import a firefox bookmark file for a user (optional)
```
stack exec migration -- importfirefoxbookmarks --conn espial.sqlite3 --userName myusername --bookmarkFile firefox-bookmarks.json
```

**Comment by gregf** [comment]
Thank you! Worked like a charm.

```
docker-compose exec espial ./migration importfirefoxbookmarks --conn /app/data/espial.sqlite3 --userName myusername --bookmarkFile /app/data/bm.json
"348 bookmarks imported."
```
