### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by lansaloni** [jonschoning/espial#37]
I have been using espial for a few years and I have also saved URLs related to non-browser applications such as anydesk.
I have hundreds of links saved in the espial DB like this:
"anydesk: 12345678"
For a few days (perhaps with the last update) I have not been able to add URLs of this type, an error message appears with the indication 
`"Invalid URL"`
This is the detailed log:
```
POST /api/add
  Request Body: {"url":"anydesk:12345678","toread":null,"title":"TEST","time":null,"tags":"test","slug":null,"selected":null,"private":true,"description":"Anydeks TEST","bid":null,"archiveUrl":null}
  Accept: */*
  Status: 400 Bad Request 0.0014245s
```
The same thing if I try to modify an existing URL.

**Comment by jonschoning** [comment]
non-http/https schemes for bookmark urls were prevented in  commit 2d3b3c3 on 2021-09-29 .  

The purpose of this change was to prevent Stored XSS attacks i.e. to prevent storage and display of malicious script in the URL.   For example, It was possible to add urls such as `javascript:alert(document.cookie)` demonstrating execution of arbitrary javascript.

While I think that is a good default, I'm eager to help unblock you since you're getting value out of using espial for non-browser applications such as anydesk.

I'm thinking perhaps of just adding a user setting that allows non-http/https schemes (enabled at your own risk)

**Comment by lansaloni** [comment]
Access to my espial is enabled only to registered users and is used by technicians for internal purposes, so I should be safe from security problems.
When adding a user setting that allows non-http/https schemes, just let me know.

**Comment by jonschoning** [comment]
sure - I should be able to implement this fairly quickly

**Comment by jonschoning** [comment]
I ended up making this an application-level settings instead of a user setting. 

If you're using docker, you can add `- ALLOW_NON_HTTP_URL_SCHEMES=true` do your docker-compose file https://github.com/jonschoning/espial-docker/blob/master/docker-compose.yml#L20

Otherwise, you can edit settings.yml if building from source, https://github.com/jonschoning/espial/blob/368c5db5105e431b5c08017a59ec648a641e85e8/config/settings.yml#L47

or you can just set an environment variable `ALLOW_NON_HTTP_URL_SCHEMES`

**Comment by lansaloni** [comment]
I use docker and the environment variable works.
Thank you very much, I love you! :-)
